"""
evaluate.py — Evaluate the RAG pipeline against the golden set.

What this file does:
1. Loads questions from data/golden_set.json
2. Runs each question through the RAG pipeline
3. Checks if expected sections were retrieved
4. Checks if expected keywords appear in the answer
5. Prints a score for each question and an overall score

Run this file:
    python src/evaluate.py

Use this BEFORE and AFTER making changes to measure improvement.
"""

import json
import os
import psycopg2
from pathlib import Path
from sentence_transformers import SentenceTransformer
from src.dotenv import load_dotenv

try:
    from src.rag import search_chunks, build_prompt, call_claude
    from src.reranker import load_reranker, rerank
except ModuleNotFoundError:
    from rag import search_chunks, build_prompt, call_claude
    from reranker import load_reranker, rerank

# ── Load environment variables ─────────────────────────────────────────────────
load_dotenv()

# ── Config ────────────────────────────────────────────────────────────────────
GOLDEN_SET_PATH = Path("data/golden_set.json")

DB_CONFIG = {
    "host": os.getenv("DB_HOST"),
    "port": int(os.getenv("DB_PORT", "5432")),
    "dbname": os.getenv("DB_NAME"),
    "user": os.getenv("DB_USER"),
    "password": os.getenv("DB_PASSWORD")
}

EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "BAAI/bge-small-en-v1.5")
RERANKER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"


# ── Function 1: Load golden set ───────────────────────────────────────────────
def load_golden_set(path: Path) -> list[dict]:
    """Load the golden set from JSON file."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# ── Function 2: Check section retrieval ───────────────────────────────────────
def check_sections(retrieved_chunks: list[dict], expected_sections: list[str]) -> dict:
    """
    Check if the expected sections were retrieved.

    Args:
        retrieved_chunks: chunks returned by our pipeline
        expected_sections: section numbers we expected to find

    Returns:
        dict with score and details
    """
    retrieved_sections = [chunk["section"] for chunk in retrieved_chunks]

    found = []
    missing = []
    for section in expected_sections:
        if section in retrieved_sections:
            found.append(section)
        else:
            missing.append(section)

    score = len(found) / len(expected_sections) if expected_sections else 0

    return {
        "score": score,
        "found": found,
        "missing": missing
    }


# ── Function 3: Check answer keywords ─────────────────────────────────────────
def check_keywords(answer: str, expected_keywords: list[str]) -> dict:
    """
    Check if expected keywords appear in the answer.

    Args:
        answer: the answer generated by Claude
        expected_keywords: keywords we expect to find in the answer

    Returns:
        dict with score and details
    """
    answer_lower = answer.lower()

    found = []
    missing = []
    for keyword in expected_keywords:
        if keyword.lower() in answer_lower:
            found.append(keyword)
        else:
            missing.append(keyword)

    score = len(found) / len(expected_keywords) if expected_keywords else 0

    return {
        "score": score,
        "found": found,
        "missing": missing
    }


# ── Function 4: Run evaluation ─────────────────────────────────────────────────
def run_evaluation():
    """
    Run the full evaluation against the golden set.
    Prints results for each question and an overall score.
    """

    # Load golden set
    golden_set = load_golden_set(GOLDEN_SET_PATH)
    print(f"Loaded {len(golden_set)} questions from golden set\n")

    # Connect to database and load models once
    conn = psycopg2.connect(**DB_CONFIG)
    embed_model = SentenceTransformer(EMBEDDING_MODEL)
    reranker = load_reranker()

    # Track overall scores
    all_section_scores = []
    all_keyword_scores = []

    # Run each question
    for item in golden_set:
        print(f"{'='*60}")
        print(f"Question {item['id']}: {item['question']}")
        print(f"{'='*60}")

        # Step 1: Search
        chunks = search_chunks(item["question"], conn, embed_model)

        # Step 2: Rerank
        chunks = rerank(item["question"], chunks, reranker)

        # Step 3: Check sections
        section_result = check_sections(chunks, item["expected_sections"])
        print(f"Section retrieval: {section_result['score']*100:.0f}%")
        print(f"  ✅ Found:   {section_result['found']}")
        print(f"  ❌ Missing: {section_result['missing']}")

        # Step 4: Generate answer
        prompt = build_prompt(item["question"], chunks)
        answer = call_claude(prompt)

        # Step 5: Check keywords
        keyword_result = check_keywords(answer, item["expected_keywords"])
        print(f"Keyword coverage: {keyword_result['score']*100:.0f}%")
        print(f"  ✅ Found:   {keyword_result['found']}")
        print(f"  ❌ Missing: {keyword_result['missing']}")

        print(f"\nAnswer preview: {answer[:200]}...\n")

        all_section_scores.append(section_result["score"])
        all_keyword_scores.append(keyword_result["score"])

    # Overall scores
    avg_section = sum(all_section_scores) / len(all_section_scores)
    avg_keyword = sum(all_keyword_scores) / len(all_keyword_scores)
    overall = (avg_section + avg_keyword) / 2

    print(f"{'='*60}")
    print(f"OVERALL RESULTS")
    print(f"{'='*60}")
    print(f"Section retrieval score: {avg_section*100:.0f}%")
    print(f"Keyword coverage score:  {avg_keyword*100:.0f}%")
    print(f"Overall score:           {overall*100:.0f}%")

    conn.close()


if __name__ == "__main__":
    run_evaluation()